# Generated by Django 6.0.5 on 2026-06-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-date_added', '-pk'], 'verbose_name': 'Вопрос и ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
    ]
