# Generated by Django 6.0.5 on 2026-06-01 10:37

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Формат: +375 (29) XXX-XX-XX', max_length=20, validators=[users.models.validate_phone], verbose_name='Телефон')),
                ('birth_date', models.DateField(help_text='Только для лиц старше 18 лет', validators=[users.models.validate_age], verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
