# Generated by Django 6.0.5 on 2026-06-01 12:00

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Только для лиц старше 18 лет', null=True, validators=[pages.models.validate_age_18], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='+375 (29) XXX-XX-XX', max_length=20, validators=[pages.models.validate_phone_employee], verbose_name='Телефон'),
        ),
    ]
