# Generated by Django 6.0.5 on 2026-06-01 10:44

import car_rental.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название парка')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Автопарк',
                'verbose_name_plural': 'Автопарки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование скидки')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование штрафа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма штрафа (руб.)')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_models', to='car_rental.bodytype', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['brand', 'model_name'],
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Государственный номер')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска')),
                ('car_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость автомобиля (руб.)')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Суточная стоимость проката (руб.)')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='car_rental.carmodel', verbose_name='Модель')),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='car_rental.carpark', verbose_name='Автопарк')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['car_model__brand', 'car_model__model_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='+375 (29) XXX-XX-XX', max_length=20, validators=[car_rental.models.validate_phone], verbose_name='Телефон')),
                ('birth_date', models.DateField(validators=[car_rental.models.validate_age], verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('days_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество дней')),
                ('expected_return_date', models.DateField(editable=False, verbose_name='Ожидаемая дата возврата')),
                ('rental_sum', models.DecimalField(decimal_places=2, default=0, help_text='Суточная цена × количество дней', max_digits=12, verbose_name='Сумма проката (руб.)')),
                ('discount_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма скидки (руб.)')),
                ('fine_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма штрафов (руб.)')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='car_rental.car', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='car_rental.client', verbose_name='Клиент')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='car_rental.discount', verbose_name='Скидка')),
                ('fines', models.ManyToManyField(blank=True, related_name='rentals', to='car_rental.fine', verbose_name='Штрафы')),
            ],
            options={
                'verbose_name': 'Прокат',
                'verbose_name_plural': 'Прокаты',
                'ordering': ['-issue_date'],
            },
        ),
    ]
