# Generated by Django 6.0.5 on 2026-06-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма проката (руб.)'),
        ),
    ]
